
name: Playwright Tests
on:
  schedule:
    - cron: '*/2 * * * *' # Runs every day at midnight
  push:
    branches: [main, develop,release]
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:    
      ENVR:    
        description: ENVIRONMENT
        type: choice
        options:
        - QA
        - PROD
        - DEV
        required: true
        default: DEV
  
  
env:
  CI: true
  URL: ${{ vars.URL }}
  # ENVIRON: ${{ github.event.inputs.ENVR || 'QA' }} 
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: ${{inputs.ENVR || vars.ENVIRON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install library
        run: npm ci
      - name: install playwright browser
        run: npx playwright install --with-deps
      - name: run playwright test
        run: npx playwright test
