
name: Playwright Tests
on:
  schedule:
    - cron: '*/2 * * * *' # Runs every day at midnight
  push:
    branches: [main, develop,release]
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:    
      ENVR:    
        description: ENVIRONMENT
        type: choice
        options:
        - QA
        - PROD
        - DEV
        required: true
        default: DEV
  
  
env:
  CI: true
  URL: ${{ vars.URL }}
  # ENVIRON: ${{ github.event.inputs.ENVR || 'QA' }} 
jobs:
  Job1:
    runs-on: ubuntu-latest
    outputs:
      sahoo: ${{steps.install-playwright.outputs.om}}
      sahoo1: ${{steps.install-playwright.outputs.om2}}
    environment: ${{inputs.ENVR || vars.ENVIRON }}
    strategy:
      matrix:
        name:
         - lol
         - lol1
         - lol2
        name2:
         - lol3
         - lol4
         - lol5
        # shard: [1,2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install library
        run: npm ci
      - name: install playwright browser
        id: install-playwright
        run: |
          npx playwright install --with-deps
          echo "om=${{matrix.name}}" >> $GITHUB_OUTPUT
          echo "om2=${{matrix.name2}}" >> $GITHUB_OUTPUT
      - name: run playwright test
        run: npx playwright test --shard=${{matrix.shard}}/2

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    environment: ${{inputs.ENVR || vars.ENVIRON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install library
        run: npm ci
      - name: install playwright browser
        run: |
          npx playwright install --with-deps
          echo "${{needs.Job1.outputs.sahoo}}"
          echo "${{needs.Job1.outputs.sahoo1}}"
      - name: run playwright test
        run: npx playwright test --project=chromium
      - name: upload the results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            test-results/
            playwright-report/

      
      
