
name: Playwright Tests
on:
  push:
    branches: [main, develop,release]
  pull_request:
    branches:
      - main
env:
  CI: true
  URL: ${{ vars.URL }}
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install library
        run: npm ci
      - name: install playwright browser
        run: npx playwright install --with-deps
      - name: run playwright test
        run: npx playwright test
      
