name: Schedule Test

on:
  schedule:
    - cron: "*/3 * * * *"
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"